"""Generate the self-contained Kaggle evaluation notebook for REACTOR."""

import json
from pathlib import Path

NOTEBOOK_PATH = Path("REACTOR_Kaggle_Evaluation.ipynb")


def build_notebook() -> dict:
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🎙️ REACTOR: Full-Duplex Voice Agent Evaluation on Kaggle\n",
                "**PRISM GenAI Hackathon (Theme 05: Full-Duplex Voice Agents)**  \n",
                "Evaluation of **REACTOR** against the official **NTU Full-Duplex-Bench v3 (FDB-v3)** benchmark (100 real human audio recordings).\n",
                "\n",
                "---\n",
                "\n",
                "### ⚙️ Hardware & Environment Requirements\n",
                "> [!IMPORTANT]\n",
                "> - **Accelerator:** Select **GPU T4 x2** in the right-hand panel (`Notebook Options` → `Accelerator` → `GPU T4 x2`).\n",
                ">   * *Why not TPU v5e-8?* Full-Duplex-Bench uses NVIDIA NeMo Parakeet ASR (`nvidia/parakeet-tdt-0.6b-v2`), which compiles CUDA C++ kernels and Triton routines. Google TPU cannot execute PyTorch CUDA binaries.\n",
                "> - **Internet:** Must be toggled **ON** (`Settings` → `Internet` → `On`).\n",
                "> - **Kaggle Secrets:** Add the following keys in Kaggle menu **Add-ons → Secrets**:\n",
                ">   - `LIVEKIT_URL`: Your LiveKit Cloud WebSocket URL (`wss://<project>.livekit.cloud`)\n",
                ">   - `LIVEKIT_API_KEY`: Your LiveKit API Key\n",
                ">   - `LIVEKIT_API_SECRET`: Your LiveKit API Secret\n",
                ">   - `GOOGLE_API_KEY`: Your Google Gemini API Key\n",
                ">   - *(Optional)* `OPENAI_API_KEY`: Only if running with `--use-llm` for the semantic LLM judge.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Verify NVIDIA GPU & CUDA environment\n",
                "import os\n",
                "import subprocess\n",
                "import sys\n",
                "import torch\n",
                "\n",
                'print(f"Python executable: {sys.executable}")\n',
                'print(f"Python version: {sys.version.split()[0]}")\n',
                'print(f"PyTorch version: {torch.__version__}")\n',
                'print(f"CUDA available: {torch.cuda.is_available()}")\n',
                "\n",
                "if not torch.cuda.is_available():\n",
                "    raise RuntimeError(\n",
                "        \"❌ CUDA GPU is not available! In the right sidebar, change Accelerator to 'GPU T4 x2'.\"\n",
                "    )\n",
                "\n",
                'print(f"GPU device count: {torch.cuda.device_count()}")\n',
                "for i in range(torch.cuda.device_count()):\n",
                '    print(f"  Device {i}: {torch.cuda.get_device_name(i)}")\n',
                "\n",
                "!nvidia-smi --query-gpu=name,memory.total,memory.free --format=csv\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Install required system packages (ffmpeg, libsndfile, espeak-ng)\n",
                "!apt-get update -qq && apt-get install -y -qq ffmpeg libsndfile1 espeak-ng git > /dev/null\n",
                "!ffmpeg -version | head -n 1\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 3. Setup REACTOR codebase\n",
                "from pathlib import Path\n",
                "import os, sys\n",
                "\n",
                "CWD = Path.cwd()\n",
                'if (CWD / "src" / "reactor").is_dir():\n',
                "    REPO_DIR = CWD\n",
                'elif (Path("/kaggle/working/REACTOR") / "src" / "reactor").is_dir():\n',
                '    REPO_DIR = Path("/kaggle/working/REACTOR")\n',
                "else:\n",
                '    REPO_DIR = Path("/kaggle/working/REACTOR")\n',
                '    print("Cloning REACTOR repository...")\n',
                "    !git clone https://github.com/0xkhush/REACTOR.git {REPO_DIR}\n",
                "\n",
                "os.chdir(REPO_DIR)\n",
                'sys.path.insert(0, str(REPO_DIR / "src"))\n',
                'print(f"✅ Active repository root: {REPO_DIR}")\n',
                "!git status -s || true\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4. Install Python dependencies\n",
                "# LiveKit voice agent framework & Google plugin\n",
                '!pip install -q "livekit-agents==1.3.12" "livekit-plugins-google==1.3.12"\n',
                "\n",
                "# NVIDIA NeMo Parakeet ASR and audio utilities required by FDB-v3\n",
                '!pip install -q "nemo_toolkit[asr]==2.5.3" "pydub==0.25.1" "ffmpeg-python==0.2.0"\n',
                "\n",
                "# Install REACTOR in editable mode with development & voice extras\n",
                '!pip install -q -e ".[dev,voice]"\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 5. Configure credentials from Kaggle Secrets into .env.local\n",
                "from pathlib import Path\n",
                "import os\n",
                "\n",
                'livekit_url = ""\n',
                'livekit_key = ""\n',
                'livekit_secret = ""\n',
                'google_key = ""\n',
                'openai_key = ""\n',
                "\n",
                "try:\n",
                "    from kaggle_secrets import UserSecretsClient\n",
                "    client = UserSecretsClient()\n",
                '    livekit_url = client.get_secret("LIVEKIT_URL")\n',
                '    livekit_key = client.get_secret("LIVEKIT_API_KEY")\n',
                '    livekit_secret = client.get_secret("LIVEKIT_API_SECRET")\n',
                '    google_key = client.get_secret("GOOGLE_API_KEY")\n',
                "    try:\n",
                '        openai_key = client.get_secret("OPENAI_API_KEY")\n',
                "    except Exception:\n",
                '        openai_key = ""\n',
                "except Exception as e:\n",
                '    print(f"Kaggle Secrets client notice: {e}")\n',
                "\n",
                "# Fallback to os.environ if set manually\n",
                'livekit_url = livekit_url or os.getenv("LIVEKIT_URL", "")\n',
                'livekit_key = livekit_key or os.getenv("LIVEKIT_API_KEY", "")\n',
                'livekit_secret = livekit_secret or os.getenv("LIVEKIT_API_SECRET", "")\n',
                'google_key = google_key or os.getenv("GOOGLE_API_KEY", "")\n',
                'openai_key = openai_key or os.getenv("OPENAI_API_KEY", "")\n',
                "\n",
                "missing = []\n",
                'if not livekit_url or not livekit_url.startswith("wss://"): missing.append("LIVEKIT_URL")\n',
                'if not livekit_key: missing.append("LIVEKIT_API_KEY")\n',
                'if not livekit_secret: missing.append("LIVEKIT_API_SECRET")\n',
                'if not google_key: missing.append("GOOGLE_API_KEY")\n',
                "\n",
                "if missing:\n",
                "    raise ValueError(\n",
                '        f"❌ Missing required secrets: {missing}. Please add them via Kaggle menu: Add-ons -> Secrets"\n',
                "    )\n",
                "\n",
                "env_lines = [\n",
                '    "# Configured by REACTOR Kaggle Evaluation Notebook",\n',
                '    "REACTOR_MODE=benchmark",\n',
                '    f"LIVEKIT_URL={livekit_url}",\n',
                '    f"LIVEKIT_API_KEY={livekit_key}",\n',
                '    f"LIVEKIT_API_SECRET={livekit_secret}",\n',
                '    f"GOOGLE_API_KEY={google_key}",\n',
                '    "GOOGLE_LIVE_MODEL=gemini-2.5-flash",\n',
                '    "REACTOR_FREE_QUOTA_CONFIRMED=yes",\n',
                "]\n",
                "if openai_key:\n",
                '    env_lines.append(f"OPENAI_API_KEY={openai_key}")\n',
                "\n",
                'Path(".env.local").write_text("\\n".join(env_lines) + "\\n")\n',
                'Path(".env.local").chmod(0o600)\n',
                'print("✅ .env.local created successfully with confirmed permissions.")\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 6. Fetch upstream Full-Duplex-Bench and download released audio dataset\n",
                "!python scripts/setup_fdb.py --destination vendor/Full-Duplex-Bench --with-data\n",
                "\n",
                "# Verify dataset\n",
                'dataset_path = Path("fdb_v3_data_released")\n',
                'wav_files = sorted(dataset_path.glob("*/input.wav"))\n',
                'print(f"✅ Verified {len(wav_files)}/100 benchmark input.wav recordings in {dataset_path}")\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 7. Run full unit test suite (203 tests) and offline preflight\n",
                'print("Running pytest unit test suite...")\n',
                "!python -m pytest -q\n",
                "\n",
                'print("\\nRunning offline benchmark preflight check...")\n',
                "!python scripts/reproduce.py --check\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 8. Execute Full Benchmark Reproduction\n",
                "# Runs live worker, streams all 100 benchmark audio recordings,\n",
                "# runs NeMo Parakeet ASR, and generates evaluation JSONs.\n",
                "import subprocess\n",
                "import sys\n",
                "\n",
                'cmd = [sys.executable, "scripts/reproduce.py"]\n',
                "if openai_key:\n",
                '    print("OPENAI_API_KEY detected: Running with --use-llm (semantic evaluator)")\n',
                '    cmd.append("--use-llm")\n',
                "else:\n",
                '    print("Running with exact-match evaluator (no OpenAI key needed)")\n',
                "\n",
                'print(f"🚀 Executing: {\' \'.join(cmd)}\\n")\n',
                "proc = subprocess.Popen(\n",
                "    cmd,\n",
                "    stdout=subprocess.PIPE,\n",
                "    stderr=subprocess.STDOUT,\n",
                "    text=True,\n",
                "    bufsize=1\n",
                ")\n",
                "\n",
                "for line in iter(proc.stdout.readline, ''):\n",
                "    print(line, end='', flush=True)\n",
                "\n",
                "proc.stdout.close()\n",
                "code = proc.wait()\n",
                "if code != 0:\n",
                '    worker_log = Path("/tmp/reactor_agent.log")\n',
                "    if worker_log.exists():\n",
                '        print("\\n--- LiveKit Worker Log (tail 50 lines) ---")\n',
                "        lines = worker_log.read_text().splitlines()[-50:]\n",
                '        print("\\n".join(lines))\n',
                '    raise RuntimeError(f"Reproduction script failed with return code {code}")\n',
                "\n",
                'print("\\n✅ Benchmark execution and scoring finished successfully!")\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 9. Summary & Metrics Display\n",
                "import json\n",
                "from pathlib import Path\n",
                "\n",
                'artifacts_dir = Path("artifacts")\n',
                'print("=" * 65)\n',
                'print("📊 REACTOR BENCHMARK EVALUATION RESULTS")\n',
                'print("=" * 65)\n',
                "\n",
                'acc_files = sorted(artifacts_dir.glob("tool_accuracy_*.json"))\n',
                "for acc_file in acc_files:\n",
                '    print(f"\\n--- {acc_file.name} ---")\n',
                "    data = json.loads(acc_file.read_text())\n",
                "    for k, v in data.items():\n",
                "        if isinstance(v, (int, float, str, bool)):\n",
                '            print(f"  {k:30s}: {v}")\n',
                "        elif isinstance(v, dict):\n",
                '            print(f"  {k}:")\n',
                "            for sub_k, sub_v in v.items():\n",
                "                if isinstance(sub_v, (int, float, str, bool)):\n",
                '                    print(f"    {sub_k:28s}: {sub_v}")\n',
                "\n",
                'pass_files = sorted(artifacts_dir.glob("strict_pass_rate_*.json"))\n',
                "for pass_file in pass_files:\n",
                '    print(f"\\n--- {pass_file.name} ---")\n',
                "    data = json.loads(pass_file.read_text())\n",
                "    for k, v in data.items():\n",
                "        if isinstance(v, (int, float, str, bool)):\n",
                '            print(f"  {k:30s}: {v}")\n',
                "        elif isinstance(v, dict):\n",
                '            print(f"  {k}:")\n',
                "            for sub_k, sub_v in v.items():\n",
                "                if isinstance(sub_v, (int, float, str, bool)):\n",
                '                    print(f"    {sub_k:28s}: {sub_v}")\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 10. Package results into downloadable ZIP archive\n",
                "import zipfile\n",
                "from pathlib import Path\n",
                "\n",
                'zip_dest = Path("/kaggle/working/REACTOR_Kaggle_Results.zip")\n',
                'with zipfile.ZipFile(zip_dest, "w", zipfile.ZIP_DEFLATED) as archive:\n',
                '    for file_path in Path("artifacts").rglob("*"):\n',
                "        if file_path.is_file():\n",
                '            archive.write(file_path, arcname=f"artifacts/{file_path.relative_to(\'artifacts\')}")\n',
                '    for log_path in [Path("/tmp/reactor_agent.log"), Path("/tmp/agent_tool_calls.log")]:\n',
                "        if log_path.is_file():\n",
                '            archive.write(log_path, arcname=f"logs/{log_path.name}")\n',
                "\n",
                'print(f"🎉 Results successfully archived: {zip_dest}")\n',
                'print(f"File size: {zip_dest.stat().st_size / 1024:.2f} KB")\n',
                'print("You can download this archive directly from the Kaggle Output file viewer!")\n',
            ],
        },
    ]

    return {
        "cells": cells,
        "metadata": {
            "accelerator": "GPU",
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.10.12",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main():
    nb = build_notebook()
    NOTEBOOK_PATH.write_text(json.dumps(nb, indent=1) + "\n")
    print(f"Generated {NOTEBOOK_PATH} with {len(nb['cells'])} cells.")


if __name__ == "__main__":
    main()
